version: '3'

services:
  app:
    build: ./study_app
    tty: true
    environment:
      MIX_ENV: dev
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      HOST: # Pass environment variables
      PORT: # Pass environment variables
    volumes:
      - ./study_app:/app:cached
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   environment:
  #     BASIC_AUTH: 'off'
  #     APP_HOSTNAME: app
  #     APP_PORT: 4000
  #   volumes:
  #     - ./public:/app/public:cached
  #     - ./docker/nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template
  #   ports:
  #     - ${WEB_PORT:-8080}:80
  #   depends_on:
  #     - app

volumes:
  db-data:
